language: python
python:
  - "3.6"
  - "3.7"
  - "3.8-dev"

dist: xenial

install:
  - pip install pipenv
  - pipenv install --dev
  - pip install codecov

script:
  - pytest --cov

after_success:
  - codecov
